language: "node_js"
jobs:
  include:
    - stage: test
      node_js: "lts/*"
      sudo: false
      script:
        - "npm install coveralls"
        - "npm run lint"
        - "npm run coverage"
        - "cat ./reports/coverage/lcov.info | ./node_modules/.bin/coveralls"
        - "npm run docs"
    - stage: compliance
      node_js: "lts/*"
      services: docker
      sudo: false
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/1.25.5/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - "npm run docker"
    - stage: pages
      node_js: "lts/*"
      sudo: false
      script:
        - "npm run docs"
      deploy:
        provider: pages
        local_dir: ./docs
        github_token: $GITHUB_API_KEY
        skip_cleanup: true
        on:
          tags: true
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
    - develop
    - alpha
    - beta
